title: Tuxink
logo: assets/svg/logomin.svg
description: Open ePaper Hardware
show_downloads: false
google_analytics:
# theme: jekyll-theme-minimal
theme: jekyll-theme-minimal
# remote_theme: "dracula/gh-pages"
excerpt_separator: <!--more-->
paginate: 5

plugins:
  - jekyll-figure
